package com.sqli.logparser.model;
// Generated 22 juil. 2019 11:41:41 by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonBackReference;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Fichier generated by hbm2java
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Fichier {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@NotNull
	@Column(unique = true)
	private String nom;

	@Column(name = "DateCreation")
	@Temporal(TemporalType.TIMESTAMP)
	private Date dateCreation;
	@Column(name = "DateModification")
	@Temporal(TemporalType.TIMESTAMP)
	private Date dateModification;

	@OneToMany(mappedBy = "fichier")
	@JsonBackReference
	private List<Demande> listDemandes;

}
